-- Generated by Mocodo 4.2.12

CREATE TABLE APPARTENIR (
  PRIMARY KEY (id_Utilisateur, id_point_collecte),
  id_Utilisateur    VARCHAR(42) NOT NULL,
  id_point_collecte VARCHAR(42) NOT NULL
);

CREATE TABLE AVIS (
  PRIMARY KEY (id_Avis),
  id_Avis   VARCHAR(42) NOT NULL,
  avis      VARCHAR(42),
  note      VARCHAR(42),
  date_Avis VARCHAR(42)
);

CREATE TABLE CATEGORIEDECHET (
  PRIMARY KEY (id_Type),
  id_Type  VARCHAR(42) NOT NULL,
  nom_Type VARCHAR(42)
);

CREATE TABLE COLLECTER (
  PRIMARY KEY (id_point_collecte, id_Tournee, id_Type),
  id_point_collecte VARCHAR(42) NOT NULL,
  id_Tournee        VARCHAR(42) NOT NULL,
  id_Type           VARCHAR(42) NOT NULL,
  qtecollecte       VARCHAR(42)
);

CREATE TABLE CORRESPONDRE (
  PRIMARY KEY (id_Dechet, id_Type),
  id_Dechet VARCHAR(42) NOT NULL,
  id_Type   VARCHAR(42) NOT NULL
);

CREATE TABLE DECHET (
  PRIMARY KEY (id_Dechet),
  id_Dechet  VARCHAR(42) NOT NULL,
  nom_Dechet VARCHAR(42),
  qte        VARCHAR(42),
  id_Type    VARCHAR(42)
);

CREATE TABLE DEPOSER (
  PRIMARY KEY (id_Dechet, id_Utilisateur, id_point_collecte),
  id_Dechet         VARCHAR(42) NOT NULL,
  id_Utilisateur    VARCHAR(42) NOT NULL,
  id_point_collecte VARCHAR(42) NOT NULL
);

CREATE TABLE DONNER (
  PRIMARY KEY (id_Utilisateur, id_Avis),
  id_Utilisateur VARCHAR(42) NOT NULL,
  id_Avis        VARCHAR(42) NOT NULL
);

CREATE TABLE ENTREPRISE (
  PRIMARY KEY (id_Entreprise),
  id_Entreprise  VARCHAR(42) NOT NULL,
  nom_Entreprise VARCHAR(42)
);

CREATE TABLE HISTORIQUE_DECHET (
  PRIMARY KEY (id_dechet),
  id_dechet      VARCHAR(42) NOT NULL,
  nom_dechet     VARCHAR(42),
  id_type        VARCHAR(42),
  nom_type       VARCHAR(42),
  quantite       VARCHAR(42),
  id_utilisateur VARCHAR(42)
);

CREATE TABLE POINT_DE_COLLECTE (
  PRIMARY KEY (id_point_collecte),
  id_point_collecte VARCHAR(42) NOT NULL,
  adresse           VARCHAR(42),
  nom_pt_collecte   VARCHAR(42),
  pos_x             VARCHAR(42),
  pos_y             VARCHAR(42),
  qte_max           VARCHAR(42)
);

CREATE TABLE TOURNEE (
  PRIMARY KEY (id_Tournee),
  id_Tournee    VARCHAR(42) NOT NULL,
  date_collecte VARCHAR(42),
  duree         VARCHAR(42)
);

CREATE TABLE TRAVAILLER (
  PRIMARY KEY (id_Utilisateur, id_Entreprise),
  id_Utilisateur VARCHAR(42) NOT NULL,
  id_Entreprise  VARCHAR(42) NOT NULL
);

CREATE TABLE UTILISATEUR (
  PRIMARY KEY (id_Utilisateur),
  id_Utilisateur  VARCHAR(42) NOT NULL,
  nom_Utilisateur VARCHAR(42),
  mail            VARCHAR(42),
  numtel          VARCHAR(42),
  motdepasse      VARCHAR(42),
  nom_role        VARCHAR(42)
);

ALTER TABLE APPARTENIR ADD FOREIGN KEY (id_point_collecte) REFERENCES POINT_DE_COLLECTE (id_point_collecte);
ALTER TABLE APPARTENIR ADD FOREIGN KEY (id_Utilisateur) REFERENCES UTILISATEUR (id_Utilisateur);

ALTER TABLE COLLECTER ADD FOREIGN KEY (id_Type) REFERENCES CATEGORIEDECHET (id_Type);
ALTER TABLE COLLECTER ADD FOREIGN KEY (id_Tournee) REFERENCES TOURNEE (id_Tournee);
ALTER TABLE COLLECTER ADD FOREIGN KEY (id_point_collecte) REFERENCES POINT_DE_COLLECTE (id_point_collecte);

ALTER TABLE CORRESPONDRE ADD FOREIGN KEY (id_Type) REFERENCES CATEGORIEDECHET (id_Type);
ALTER TABLE CORRESPONDRE ADD FOREIGN KEY (id_Dechet) REFERENCES DECHET (id_Dechet);

ALTER TABLE DEPOSER ADD FOREIGN KEY (id_point_collecte) REFERENCES POINT_DE_COLLECTE (id_point_collecte);
ALTER TABLE DEPOSER ADD FOREIGN KEY (id_Utilisateur) REFERENCES UTILISATEUR (id_Utilisateur);
ALTER TABLE DEPOSER ADD FOREIGN KEY (id_Dechet) REFERENCES DECHET (id_Dechet);

ALTER TABLE DONNER ADD FOREIGN KEY (id_Avis) REFERENCES AVIS (id_Avis);
ALTER TABLE DONNER ADD FOREIGN KEY (id_Utilisateur) REFERENCES UTILISATEUR (id_Utilisateur);

ALTER TABLE TRAVAILLER ADD FOREIGN KEY (id_Entreprise) REFERENCES ENTREPRISE (id_Entreprise);
ALTER TABLE TRAVAILLER ADD FOREIGN KEY (id_Utilisateur) REFERENCES UTILISATEUR (id_Utilisateur);
