-- Generated by Mocodo 4.2.11

CREATE TABLE CATEGORIEDECHET (
  PRIMARY KEY (id_Type),
  id_Type  VARCHAR(42) NOT NULL,
  nom_Type VARCHAR(42)
);

CREATE TABLE COLLECTER (
  PRIMARY KEY (id_point_collecte, id_Type, id_Tournee),
  id_point_collecte VARCHAR(42) NOT NULL,
  id_Type           VARCHAR(42) NOT NULL,
  id_Tournee        VARCHAR(42) NOT NULL,
  qte_collecte      VARCHAR(42)
);

CREATE TABLE DECHET (
  PRIMARY KEY (id_Dechet),
  id_Dechet  VARCHAR(42) NOT NULL,
  nom_Dechet VARCHAR(42),
  qte        VARCHAR(42),
  id_Type    VARCHAR(42) NOT NULL
);

CREATE TABLE DEPOSER (
  PRIMARY KEY (id_Dechet, id_Utilisateur, id_point_collecte),
  id_Dechet         VARCHAR(42) NOT NULL,
  id_Utilisateur    VARCHAR(42) NOT NULL,
  id_point_collecte VARCHAR(42) NOT NULL
);

CREATE TABLE ENTREPRISE (
  PRIMARY KEY (id_Entreprise),
  id_Entreprise  VARCHAR(42) NOT NULL,
  nom_Entreprise VARCHAR(42)
);

CREATE TABLE POINT_DE_COLLECTE (
  PRIMARY KEY (id_point_collecte),
  id_point_collecte VARCHAR(42) NOT NULL,
  adresse           VARCHAR(42),
  nom_pt_collecte   VARCHAR(42),
  pos_x             VARCHAR(42),
  pos_y             VARCHAR(42),
  qte_max           VARCHAR(42)
);

CREATE TABLE TOURNEE (
  PRIMARY KEY (id_Tournee),
  id_Tournee    VARCHAR(42) NOT NULL,
  date_collecte VARCHAR(42)
);

CREATE TABLE UTILISATEUR (
  PRIMARY KEY (id_Utilisateur),
  id_Utilisateur  VARCHAR(42) NOT NULL,
  nom_Utilisateur VARCHAR(42),
  mail            VARCHAR(42),
  numtel          VARCHAR(42),
  motdepasse      VARCHAR(42),
  nom_role        VARCHAR(42),
  id_Entreprise   VARCHAR(42) NULL
);

ALTER TABLE COLLECTER ADD FOREIGN KEY (id_Tournee) REFERENCES TOURNEE (id_Tournee);
ALTER TABLE COLLECTER ADD FOREIGN KEY (id_Type) REFERENCES CATEGORIEDECHET (id_Type);
ALTER TABLE COLLECTER ADD FOREIGN KEY (id_point_collecte) REFERENCES POINT_DE_COLLECTE (id_point_collecte);

ALTER TABLE DECHET ADD FOREIGN KEY (id_Type) REFERENCES CATEGORIEDECHET (id_Type);

ALTER TABLE DEPOSER ADD FOREIGN KEY (id_point_collecte) REFERENCES POINT_DE_COLLECTE (id_point_collecte);
ALTER TABLE DEPOSER ADD FOREIGN KEY (id_Utilisateur) REFERENCES UTILISATEUR (id_Utilisateur);
ALTER TABLE DEPOSER ADD FOREIGN KEY (id_Dechet) REFERENCES DECHET (id_Dechet);

ALTER TABLE UTILISATEUR ADD FOREIGN KEY (id_Entreprise) REFERENCES ENTREPRISE (id_Entreprise);
